<a href="https://colab.research.google.com/github/Viera1624/TelecomX_LATAM/blob/main/telecomx_latam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Trello del desafío](https://trello.com/b/Va6JwjjL/telecomxlatam)

#📌 Extracción

In [255]:
import pandas as pd

In [256]:
datos_clientes = pd.read_json('/content/TelecomX_Data.json')
datos_clientes.head()

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."

##Normalizando Json

In [257]:
def normalizar_json(columna):
  df_norm = pd.json_normalize(datos_clientes[columna])

  return df_norm

customer = normalizar_json('customer')
phone = normalizar_json('phone')
internet = normalizar_json('internet')
account = normalizar_json('account')

In [258]:
datos_clientes_norm = pd.concat([datos_clientes[['customerID', 'Churn']],
                                 customer, phone, internet, account],
                                axis=1)
datos_clientes_norm

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.9
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.6

#🔧 Transformación

##Verificando si hay valores nulos, duplicados o errores de formato

In [259]:
datos_clientes_norm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7267 non-null   object
 1   Churn             7267 non-null   object
 2   gender            7267 non-null   object
 3   SeniorCitizen     7267 non-null   int64
 4   Partner           7267 non-null   object
 5   Dependents        7267 non-null   object
 6   tenure            7267 non-null   int64
 7   PhoneService      7267 non-null   object
 8   MultipleLines     7267 non-null   object
 9   InternetService   7267 non-null   object
 10  OnlineSecurity    7267 non-null   object
 11  OnlineBackup      7267 non-null   object
 12  DeviceProtection  7267 non-null   object
 13  TechSupport       7267 non-null   object
 14  StreamingTV       7267 non-null   object
 15  StreamingMovies   7267 non-null   object
 16  Contract          7267 non-null   object
 17  PaperlessBilling  7267 non-null   object
 18  PaymentMethod     7267 non-null   object
 19  Charges.Monthly   7267 non-null   float64
 20  Charges.Total     7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [260]:
datos_clientes_norm.dtypes

customerID           object
Churn                object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
Charges.Monthly     float64
Charges.Total        object
dtype: object

In [261]:
x =datos_clientes_norm['customerID'].unique()

In [262]:
len(x)

7267

##Normalizando las columnaas

In [263]:
datos_clientes_norm.columns = datos_clientes_norm.columns.str.replace('.', '')
datos_clientes_norm.head()

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,ChargesMonthly,ChargesTotal
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

###Renombrar las columnaas

In [264]:
columnas = list(datos_clientes_norm.columns)

columnas_nuevas = ['ID_Cliente','Retirado','Genero','Mayor_65_Años','Tiene_Pareja','Dependientes',
                    'Meses_De_Contrato','Servicio_Telefonico','Multiples_Lineas','Servicio_Internet','Seguridad_En_linea',
                    'Respaldo_En_linea','Proteccion_Del_Dispositivo','Soporte_Tecnico','Television_Por_Cable','Streaming_Peliculas',
                    'Tipo_De_Contrato', 'Factura_En_Linea','Metodo_De_Pago', 'Total_Por_Mes',
                    'Total_Gastado']

renombrar = dict(zip(columnas,columnas_nuevas))

In [265]:
datos_clientes_norm.rename(columns=renombrar, inplace=True)
datos_clientes_norm.head(1)

,ID_Cliente,Retirado,Genero,Mayor_65_Años,Tiene_Pareja,Dependientes,Meses_De_Contrato,Servicio_Telefonico,Multiples_Lineas,Servicio_Internet,...,Respaldo_En_linea,Proteccion_Del_Dispositivo,Soporte_Tecnico,Television_Por_Cable,Streaming_Peliculas,Tipo_De_Contrato,Factura_En_Linea,Metodo_De_Pago,Total_Por_Mes,Total_Gastado
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3

##Transformando datos numéricos

Alintentar transformar el tipo de datos de la columna Total_Gastado a float encontramos que hay espacios entre los registros, vamos a verificar

In [266]:
datos_clientes_norm[datos_clientes_norm['Total_Gastado'].str.contains('\ ', na= False)]

<>:1: SyntaxWarning: invalid escape sequence '\ '
<>:1: SyntaxWarning: invalid escape sequence '\ '
/tmp/ipython-input-4215343052.py:1: SyntaxWarning: invalid escape sequence '\ '
  datos_clientes_norm[datos_clientes_norm['Total_Gastado'].str.contains('\ ', na= False)]

,ID_Cliente,Retirado,Genero,Mayor_65_Años,Tiene_Pareja,Dependientes,Meses_De_Contrato,Servicio_Telefonico,Multiples_Lineas,Servicio_Internet,...,Respaldo_En_linea,Proteccion_Del_Dispositivo,Soporte_Tecnico,Television_Por_Cable,Streaming_Peliculas,Tipo_De_Contrato,Factura_En_Linea,Metodo_De_Pago,Total_Por_Mes,Total_Gastado
975,1371-DWPAZ,No,Female,0,Yes,Yes,0,No,No phone service,DSL,...,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,
1775,2520-SGTTA,No,Female,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,
1955,2775-SEFEE,No,Male,0,No,Yes,0,Yes,Yes,DSL,...,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,
2075,2923-ARZLG,No,Male,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,
2232,3115-CZMZD,No,Male,0,No,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,
2308,3213-VVOLG,No,Male,0,Yes,Yes,0,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,
2930,4075-WKNIU,No,Female,0,Yes,Yes,0,Yes,Yes,DSL,...,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,
3134,4367-NUYAO,No,Male,0,Yes,Yes,0,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,
3203,4472-LVYGI,No,Female,0,Yes,Yes,0,No,No phone service,DSL,...,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,
4169,5709-LVOEQ,No,Female,0,Yes,Yes,0,Yes,No,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,
5599,7644-OMVMY,No,Male,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,

Una vez encontrados los registros que tienen espacios, podemos observar que coinciden con el numero 0(cero) en la columna Meses_De_Contrato, esto puede indicar que son clientes nuevos y por lo tanto, no han acumulado un cargo total. Vamos a verificar si hay más clientes nuevos

In [267]:
datos_clientes_norm.query('Meses_De_Contrato == 0')

,ID_Cliente,Retirado,Genero,Mayor_65_Años,Tiene_Pareja,Dependientes,Meses_De_Contrato,Servicio_Telefonico,Multiples_Lineas,Servicio_Internet,...,Respaldo_En_linea,Proteccion_Del_Dispositivo,Soporte_Tecnico,Television_Por_Cable,Streaming_Peliculas,Tipo_De_Contrato,Factura_En_Linea,Metodo_De_Pago,Total_Por_Mes,Total_Gastado
975,1371-DWPAZ,No,Female,0,Yes,Yes,0,No,No phone service,DSL,...,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,
1775,2520-SGTTA,No,Female,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,
1955,2775-SEFEE,No,Male,0,No,Yes,0,Yes,Yes,DSL,...,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,
2075,2923-ARZLG,No,Male,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,
2232,3115-CZMZD,No,Male,0,No,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,
2308,3213-VVOLG,No,Male,0,Yes,Yes,0,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,
2930,4075-WKNIU,No,Female,0,Yes,Yes,0,Yes,Yes,DSL,...,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,
3134,4367-NUYAO,No,Male,0,Yes,Yes,0,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,
3203,4472-LVYGI,No,Female,0,Yes,Yes,0,No,No phone service,DSL,...,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,
4169,5709-LVOEQ,No,Female,0,Yes,Yes,0,Yes,No,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,
5599,7644-OMVMY,No,Male,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,

los resultados obtenidos coinciden con ceros en tenure y espacios en ChargesTotal, procedemos entonces a reemplazar espacios por ceros y realizar la respectiva transformación

In [268]:
datos_clientes_norm['Total_Gastado']= datos_clientes_norm['Total_Gastado'].replace('\ ', '0', regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\ '
<>:1: SyntaxWarning: invalid escape sequence '\ '
/tmp/ipython-input-3318985259.py:1: SyntaxWarning: invalid escape sequence '\ '
  datos_clientes_norm['Total_Gastado']= datos_clientes_norm['Total_Gastado'].replace('\ ', '0', regex=True)

In [269]:
import numpy as np
datos_clientes_norm['Total_Gastado']= datos_clientes_norm['Total_Gastado'].astype(np.float64)

In [270]:
datos_clientes_norm.head(1)

,ID_Cliente,Retirado,Genero,Mayor_65_Años,Tiene_Pareja,Dependientes,Meses_De_Contrato,Servicio_Telefonico,Multiples_Lineas,Servicio_Internet,...,Respaldo_En_linea,Proteccion_Del_Dispositivo,Soporte_Tecnico,Television_Por_Cable,Streaming_Peliculas,Tipo_De_Contrato,Factura_En_Linea,Metodo_De_Pago,Total_Por_Mes,Total_Gastado
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3

In [271]:
transformar = ['Retirado','Tiene_Pareja','Dependientes',
               'Servicio_Telefonico','Multiples_Lineas','Seguridad_En_linea',
               'Respaldo_En_linea','Proteccion_Del_Dispositivo','Soporte_Tecnico','Television_Por_Cable','Streaming_Peliculas',
               'Factura_En_Linea']

In [272]:
datos_clientes_norm[transformar] = datos_clientes_norm[transformar].apply(lambda x: x.replace('Yes', '1').replace('No', '0'))
datos_clientes_norm.head(3)

,ID_Cliente,Retirado,Genero,Mayor_65_Años,Tiene_Pareja,Dependientes,Meses_De_Contrato,Servicio_Telefonico,Multiples_Lineas,Servicio_Internet,...,Respaldo_En_linea,Proteccion_Del_Dispositivo,Soporte_Tecnico,Television_Por_Cable,Streaming_Peliculas,Tipo_De_Contrato,Factura_En_Linea,Metodo_De_Pago,Total_Por_Mes,Total_Gastado
0,0002-ORFBO,0,Female,0,1,1,9,1,0,DSL,...,1,0,1,1,0,One year,1,Mailed check,65.6,593.30
1,0003-MKNFE,0,Male,0,0,0,9,1,1,DSL,...,0,0,0,0,1,Month-to-month,0,Mailed check,59.9,542.40
2,0004-TLHLJ,1,Male,0,0,0,4,1,0,Fiber optic,...,0,1,0,0,0,Month-to-month,1,Electronic check,73.9,280.85

In [274]:
for columna in datos_clientes_norm.columns:
    print(f"Valores unicos para la columna '{columna}':")
    print(datos_clientes_norm[columna].unique())
    print("\n")

Valores unicos para la columna 'ID_Cliente':
['0002-ORFBO' '0003-MKNFE' '0004-TLHLJ' ... '9992-UJOEL' '9993-LHIEB'
 '9995-HOTOH']


Valores unicos para la columna 'Retirado':
['0' '1' '']


Valores unicos para la columna 'Genero':
['Female' 'Male']


Valores unicos para la columna 'Mayor_65_Años':
[0 1]


Valores unicos para la columna 'Tiene_Pareja':
['1' '0']


Valores unicos para la columna 'Dependientes':
['1' '0']


Valores unicos para la columna 'Meses_De_Contrato':
[ 9  4 13  3 71 63  7 65 54 72  5 56 34  1 45 50 23 55 26 69 11 37 49 66
 67 20 43 59 12 27  2 25 29 14 35 64 39 40  6 30 70 57 58 16 32 33 10 21
 61 15 44 22 24 19 47 62 46 52  8 60 48 28 41 53 68 51 31 36 17 18 38 42
  0]


Valores unicos para la columna 'Servicio_Telefonico':
['1' '0']


Valores unicos para la columna 'Multiples_Lineas':
['0' '1' 'No phone service']


Valores unicos para la columna 'Servicio_Internet':
['DSL' 'Fiber optic' 'No']


Valores unicos para la columna 'Seguridad_En_linea':
['0' '1' 'No internet service']


Valores unicos para la columna 'Respaldo_En_linea':
['1' '0' 'No internet service']


Valores unicos para la columna 'Proteccion_Del_Dispositivo':
['0' '1' 'No internet service']


Valores unicos para la columna 'Soporte_Tecnico':
['1' '0' 'No internet service']


Valores unicos para la columna 'Television_Por_Cable':
['1' '0' 'No internet service']


Valores unicos para la columna 'Streaming_Peliculas':
['0' '1' 'No internet service']


Valores unicos para la columna 'Tipo_De_Contrato':
['One year' 'Month-to-month' 'Two year']


Valores unicos para la columna 'Factura_En_Linea':
['1' '0']


Valores unicos para la columna 'Metodo_De_Pago':
['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']


Valores unicos para la columna 'Total_Por_Mes':
[65.6  59.9  73.9  ... 91.75 68.8  67.85]


Valores unicos para la columna 'Total_Gastado':
[ 593.3   542.4   280.85 ...  742.9  4627.65 3707.6 ]

In [195]:
datos_clientes_norm[transformar].astype(np.int64)

ValueError: invalid literal for int() with base 10: ''

In [273]:
datos_clientes_norm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID_Cliente                  7267 non-null   object
 1   Retirado                    7267 non-null   object
 2   Genero                      7267 non-null   object
 3   Mayor_65_Años               7267 non-null   int64
 4   Tiene_Pareja                7267 non-null   object
 5   Dependientes                7267 non-null   object
 6   Meses_De_Contrato           7267 non-null   int64
 7   Servicio_Telefonico         7267 non-null   object
 8   Multiples_Lineas            7267 non-null   object
 9   Servicio_Internet           7267 non-null   object
 10  Seguridad_En_linea          7267 non-null   object
 11  Respaldo_En_linea           7267 non-null   object
 12  Proteccion_Del_Dispositivo  7267 non-null   object
 13  Soporte_Tecnico             7267 non-null   object
 14  Television_Por_Cable        7267 non-null   object
 15  Streaming_Peliculas         7267 non-null   object
 16  Tipo_De_Contrato            7267 non-null   object
 17  Factura_En_Linea            7267 non-null   object
 18  Metodo_De_Pago              7267 non-null   object
 19  Total_Por_Mes               7267 non-null   float64
 20  Total_Gastado               7267 non-null   float64
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

##Creacion de columna Cuentas_Diarias

In [152]:
datos_clientes_norm['Cuentas_Diarias'] = (datos_clientes_norm['Total_Por_Mes']/30).round(2)

In [153]:
datos_clientes_norm.head(2)

,ID_Cliente,Retirado,Genero,Mayor_65_Años,Tiene_Pareja,Dependientes,Meses_De_Contrato,Servicio_Telefonico,Multiples_Lineas,Servicio_Internet,...,Proteccion_Del_Dispositivo,Soporte_Tecnico,Television_Por_Cable,Streaming_Peliculas,Tipo_De_Contrato,Factura_En_Linea,Metodo_De_Pago,Total_Por_Mes,Total_Gastado,Cuentas_Diarias
0,0002-ORFBO,0,Female,0,1,1,9,1,0,DSL,...,0,1,1,0,One year,1,Mailed check,65.6,593.3,2.19
1,0003-MKNFE,0,Male,0,0,0,9,1,1,DSL,...,0,0,0,1,Month-to-month,0,Mailed check,59.9,542.4,2.00

#📊 Carga y análisis

#📄Informe final